### ISSUE TITLE
Error after 1.34 upgrade

### ISSUE THREAD

**Issue by leeoocca** [lkucharczyk/mediawiki-PortableInfobox#25]
After I upgraded to 1.34 the extension seems to be giving problems.

I get this error on all the pages which featured the Infobox:

```
[XnF7jb6KCJ4A@Pnts55l8wAAAB8] /index.php/Nicola_Destro Error from line 30 of /home/vp3855fk/bagattian.ml/extensions/PortableInfobox/includes/services/Helpers/PortableInfoboxTemplateEngine.php: Call to undefined method ObjectCache::getMainWANInstance()

Backtrace:

#0 /home/vp3855fk/bagattian.ml/extensions/PortableInfobox/includes/services/PortableInfoboxRenderService.php(14): PortableInfobox\Helpers\PortableInfoboxTemplateEngine->__construct()
#1 /home/vp3855fk/bagattian.ml/extensions/PortableInfobox/includes/controllers/PortableInfoboxParserTagController.php(68): PortableInfoboxRenderService->__construct()
#2 /home/vp3855fk/bagattian.ml/extensions/PortableInfobox/includes/controllers/PortableInfoboxParserTagController.php(124): PortableInfoboxParserTagController->render(string, Parser, PPTemplateFrame_Hash, array)
#3 /home/vp3855fk/bagattian.ml/includes/parser/Parser.php(4293): PortableInfoboxParserTagController->renderInfobox(string, array, Parser, PPTemplateFrame_Hash)
#4 /home/vp3855fk/bagattian.ml/includes/parser/PPFrame_Hash.php(328): Parser->extensionSubstitution(array, PPTemplateFrame_Hash)
#5 /home/vp3855fk/bagattian.ml/includes/parser/Parser.php(3697): PPFrame_Hash->expand(PPNode_Hash_Tree)
#6 /home/vp3855fk/bagattian.ml/includes/parser/PPFrame_Hash.php(254): Parser->braceSubstitution(array, PPFrame_Hash)
#7 /home/vp3855fk/bagattian.ml/includes/parser/Parser.php(3330): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#8 /home/vp3855fk/bagattian.ml/includes/parser/Parser.php(1489): Parser->replaceVariables(string)
#9 /home/vp3855fk/bagattian.ml/includes/parser/Parser.php(593): Parser->internalParse(string)
#10 /home/vp3855fk/bagattian.ml/includes/content/WikitextContent.php(368): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#11 /home/vp3855fk/bagattian.ml/includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#12 /home/vp3855fk/bagattian.ml/includes/Revision/RenderedRevision.php(264): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#13 /home/vp3855fk/bagattian.ml/includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#14 /home/vp3855fk/bagattian.ml/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#15 /home/vp3855fk/bagattian.ml/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#16 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#17 /home/vp3855fk/bagattian.ml/includes/Revision/RenderedRevision.php(198): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#18 /home/vp3855fk/bagattian.ml/includes/poolcounter/PoolWorkArticleView.php(196): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#19 /home/vp3855fk/bagattian.ml/includes/poolcounter/PoolCounterWork.php(125): PoolWorkArticleView->doWork()
#20 /home/vp3855fk/bagattian.ml/includes/page/Article.php(791): PoolCounterWork->execute()
#21 /home/vp3855fk/bagattian.ml/includes/actions/ViewAction.php(63): Article->view()
#22 /home/vp3855fk/bagattian.ml/includes/MediaWiki.php(511): ViewAction->show()
#23 /home/vp3855fk/bagattian.ml/includes/MediaWiki.php(302): MediaWiki->performAction(Article, Title)
#24 /home/vp3855fk/bagattian.ml/includes/MediaWiki.php(900): MediaWiki->performRequest()
#25 /home/vp3855fk/bagattian.ml/includes/MediaWiki.php(527): MediaWiki->main()
#26 /home/vp3855fk/bagattian.ml/index.php(44): MediaWiki->run()
#27 {main}
```

**Comment by lkucharczyk** [comment]
Already fixed in #23
