### ISSUE TITLE
Cannot edit templates in 1.35

### ISSUE THREAD

**Issue by The-Foilist** [lkucharczyk/mediawiki-PortableInfobox#35]
This is using the current master branch with MW 1.35. I can create infobox templates normally, but attempting to submit an edit to an infobox template that already exists results in the following error:

[545e4e5eff1832cfec85469a] /index.php?title=Template:Character&action=submit TypeError from line 1007 of /var/www/mediawiki/includes/parser/Parser.php: Return value of Parser::getTitle() must be an instance of Title, null returned

**Backtrace**
#0 /var/www/mediawiki/includes/parser/PPFrame_Hash.php(71): Parser->getTitle()
#1 /var/www/mediawiki/includes/parser/Preprocessor_Hash.php(58): PPFrame_Hash->__construct()
#2 /var/www/mediawiki/extensions/PortableInfobox/includes/services/Helpers/PortableInfoboxParsingHelper.php(31): Preprocessor_Hash->newFrame()
#3 /var/www/mediawiki/extensions/PortableInfobox/includes/services/PortableInfoboxDataService.php(199): PortableInfobox\Helpers\PortableInfoboxParsingHelper->parseIncludeonlyInfoboxes()
#4 /var/www/mediawiki/extensions/PortableInfobox/includes/PortableInfobox.hooks.php(45): PortableInfoboxDataService->reparseArticle()
#5 /var/www/mediawiki/includes/HookContainer/HookContainer.php(320): PortableInfoboxHooks::onPageContentSave()
#6 /var/www/mediawiki/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#7 /var/www/mediawiki/includes/HookContainer/HookRunner.php(2788): MediaWiki\HookContainer\HookContainer->run()
#8 /var/www/mediawiki/includes/Storage/PageUpdater.php(768): MediaWiki\HookContainer\HookRunner->onPageContentSave()
#9 /var/www/mediawiki/includes/page/WikiPage.php(2015): MediaWiki\Storage\PageUpdater->saveRevision()
#10 /var/www/mediawiki/includes/EditPage.php(2456): WikiPage->doEditContent()
#11 /var/www/mediawiki/includes/EditPage.php(1723): EditPage->internalAttemptSave()
#12 /var/www/mediawiki/includes/EditPage.php(680): EditPage->attemptSave()
#13 /var/www/mediawiki/includes/actions/EditAction.php(71): EditPage->edit()
#14 /var/www/mediawiki/includes/actions/SubmitAction.php(38): EditAction->show()
#15 /var/www/mediawiki/includes/MediaWiki.php(527): SubmitAction->show()
#16 /var/www/mediawiki/includes/MediaWiki.php(313): MediaWiki->performAction()
#17 /var/www/mediawiki/includes/MediaWiki.php(940): MediaWiki->performRequest()
#18 /var/www/mediawiki/includes/MediaWiki.php(543): MediaWiki->main()
#19 /var/www/mediawiki/index.php(53): MediaWiki->run()
#20 /var/www/mediawiki/index.php(46): wfIndexMain()
#21 {main}

**Special:Version**
MediaWiki | 1.35.0
PHP | 7.4.3 (apache2handler)
MariaDB | 10.3.22-MariaDB-1ubuntu1
ICU | 66.1
Lua | 5.1.5

**Comment by The-Foilist** [comment]
I did some more testing, and it turns out that attempting to edit any page in the Template namespace throws the same error, even if there are no tags relating to PortableInfobox.
