### ISSUE TITLE
Database error when saving page edits

### ISSUE THREAD

**Issue by The-Foilist** [lkucharczyk/mediawiki-PortableInfobox#51]
This error arose after upgrading from MediaWiki version 1.36 to version 1.37.1. It occurs whenever I try to save an edit to any page on the wiki when PortableInfobox is installed. Here's the trace:

[34f4255574036baeaae5c094] /w/index.php?title=Main_Page&action=submit Wikimedia\Rdbms\DBUnexpectedError: The unique key array should contain a single unique index

Backtrace:

from /var/www/w/includes/libs/rdbms/database/Database.php(2315)
#0 /var/www/w/includes/libs/rdbms/database/Database.php(2286): Wikimedia\Rdbms\Database->normalizeUpsertKeys()
#1 /var/www/w/includes/libs/rdbms/database/Database.php(3454): Wikimedia\Rdbms\Database->normalizeUpsertParams()
#2 /var/www/w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->replace()
#3 /var/www/w/includes/libs/rdbms/database/DBConnRef.php(513): Wikimedia\Rdbms\DBConnRef->__call()
#4 /var/www/w/extensions/PortableInfobox/includes/services/Helpers/PagePropsProxy.php(48): Wikimedia\Rdbms\DBConnRef->replace()
#5 /var/www/w/extensions/PortableInfobox/includes/services/PortableInfoboxDataService.php(250): PortableInfobox\Helpers\PagePropsProxy->set()
#6 /var/www/w/extensions/PortableInfobox/includes/services/PortableInfoboxDataService.php(149): PortableInfoboxDataService->clear()
#7 /var/www/w/extensions/PortableInfobox/includes/PortableInfobox.hooks.php(42): PortableInfoboxDataService->delete()
#8 /var/www/w/includes/HookContainer/HookContainer.php(338): PortableInfoboxHooks::onPageContentSave()
#9 /var/www/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#10 /var/www/w/includes/HookContainer/HookRunner.php(2714): MediaWiki\HookContainer\HookContainer->run()
#11 /var/www/w/includes/Storage/PageUpdater.php(807): MediaWiki\HookContainer\HookRunner->onPageContentSave()
#12 /var/www/w/includes/page/WikiPage.php(1994): MediaWiki\Storage\PageUpdater->saveRevision()
#13 /var/www/w/includes/EditPage.php(2351): WikiPage->doUserEditContent()
#14 /var/www/w/includes/EditPage.php(1687): EditPage->internalAttemptSave()
#15 /var/www/w/includes/EditPage.php(665): EditPage->attemptSave()
#16 /var/www/w/includes/actions/EditAction.php(71): EditPage->edit()
#17 /var/www/w/includes/actions/SubmitAction.php(38): EditAction->show()
#18 /var/www/w/includes/MediaWiki.php(543): SubmitAction->show()
#19 /var/www/w/includes/MediaWiki.php(320): MediaWiki->performAction()
#20 /var/www/w/includes/MediaWiki.php(930): MediaWiki->performRequest()
#21 /var/www/w/includes/MediaWiki.php(564): MediaWiki->main()
#22 /var/www/w/index.php(53): MediaWiki->run()
#23 /var/www/w/index.php(46): wfIndexMain()
#24 {main}

**Comment by The-Foilist** [comment]
Looks like the MediaWiki 1.37 release notes include the following:

* Database::upsert() and IDatabase::replace() now only accept a single unique key. Previously, a warning was issued if there were multiple unique keys provided.

So I think the code in lines 37-49 of [PagePropsProxy.php](https://github.com/lkucharczyk/mediawiki-PortableInfobox/blob/master/includes/services/Helpers/PagePropsProxy.php) needs to be changed to only supply a single unique key.

**Comment by adgellida** [comment]
Hello, I'm very interested on this, I was investigating and trying to solve this, but I can't.
Anyone can do a PR to test it on my server please? If you need a tester I'm volunteer.

**Comment by The-Foilist** [comment]
> Hello, I'm very interested on this, I was investigating and trying to solve this, but I can't. Anyone can do a PR to test it on my server please? If you need a tester I'm volunteer.

The PR I made should fix it. I tested it on a wiki of mine and it seems to work fine. Feel free to test it yourself!

**Comment by adgellida** [comment]
Perfect, you're a pseudo-god!!! ASAP I'll test it.

**Comment by adgellida** [comment]
It works!!! @The-Foilist. Thanks. Can anyone merge this please? No error when saving a page.
